# Generated by Django 3.2.4 on 2021-07-05 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('tags', models.CharField(default='', max_length=50)),
                ('handle', models.CharField(default='', max_length=44)),
                ('body', models.CharField(default='', max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=25)),
                ('sku', models.CharField(default='', max_length=25)),
                ('barcode', models.CharField(default='', max_length=25)),
                ('quantity', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_var', to='products.product')),
            ],
        ),
    ]
